### ISSUE TITLE
Segmentation fault when running frodock cluster

### ISSUE THREAD

**Issue by jackzzs** [gaoqiweng/PROTAC-Model#1]
This may not be an issue with the modeling algorithm, but it is about ease of use.
I got an error when I ran frodockcluster or frodockcluster_gcc:
```cosole
$ frodockcluster  dock.dat target.pdb -o clust_dock_4.dat -d 4         
[1]    515799 segmentation fault (core dumped)  frodockcluster dock.dat target.pdb -o clust_dock_4.dat -d 4
```
Since Frodock is distributed in binary, I'm not sure if this is due to a different link library version, so I wanted to ask you how to run the program correctly, thanks:

1. What is your Intel mkl/gcc/glibc version? You can run the following command to view the information:
```console
icc --version
ldd --version
gcc --version
```

2. I'm using the latest version of frodock (3.12), while your article uses version 2.1, have you tested the latest version? Whether a version update results in unavailability or performance differences?

3. If only frodock version 2.1 is suitable for this protocol, since frodock version 2.1 is no longer available on website, can you please consult with the author of frodock to give an alternative download channel for version 2.1, in order to improve the usability of your method. Otherwise no one can use, test or review the protocol without contacting the frodock author, which is very inconvenient.

**Comment by gaoqiweng** [comment]
Hi! It may be caused by the installation of FRODOCK v3.12, which is compatible with my docking protocol in my computational environment. In my computer, icc is not installed. GCC is 7.3.0. ldd is 2.12.

The latest version has been tested before. In our limited benchmark, frodock v2.1 performs slightly better.

**Comment by jackzzs** [comment]
Thank you for your prompt and helpful reply. I have successfully run your program with the following environment:

```console
$ module load intel/compiler/2021.2.0 intel/mkl/2021.2.0 intel/mpi/2021.2.0 \
  rosetta/3.12 autodock-vina/1.1.2 adfrsuite/1.0 voronota/1.22.3149 frodock/2.1 openbabel/3.1.0 fcc 
```
