### ISSUE TITLE
Frodockgrid will report an error when there is a fluorine atom in the ligand

### ISSUE THREAD

**Issue by jackzzs** [gaoqiweng/PROTAC-Model#3]
When running following script, error will occur if there is a fluorine atom in the ligand. I recommand using the pdbasa tool in [pdbremix](https://github.com/boscoh/pdbremix) for ASA generation, and using the target pdb without ligand for desolvation potential map generation.
```
os.system(frodockgrid + ' target_nolig.pdb -o target_DS.ccp4 -m 3')
```

**Comment by gaoqiweng** [comment]
You should delete F atoms in the ligand as what I say in the article.

**Comment by jackzzs** [comment]
Sorry for missing details in the article, I have found a way to handle this situation, thanks.
